categories = ["Added", "Changed", "Fixed", "Improved", "Removed", "Updated"]
category_delimiters = ["[", "]"]
colored_output = true
enable_debug = true
excluded_commit_tags = []
enable_footers = true
show_commit_hash = true
show_prefix = false
sort_by = "date"
template_prefix = ""
